package cn.eastrobot.robotdev.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.6
 * 2015-01-27T10:10:00.729+08:00
 * Generated source version: 2.5.6
 * 
 */
@WebServiceClient(name = "RobotServiceWx", 
                  wsdlLocation = "file:/d:/webservice/RobotServiceWx.wsdl",
                  targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceWx") 
public class RobotServiceWx_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.eastrobot.cn/ws/RobotServiceWx", "RobotServiceWx");
    public final static QName DefaultRobotServiceWxPort = new QName("http://www.eastrobot.cn/ws/RobotServiceWx", "DefaultRobotServiceWxPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/d:/webservice/RobotServiceWx.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RobotServiceWx_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/d:/webservice/RobotServiceWx.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RobotServiceWx_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RobotServiceWx_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RobotServiceWx_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RobotServiceWx_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RobotServiceWx_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RobotServiceWx_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RobotServiceWx
     */
    @WebEndpoint(name = "DefaultRobotServiceWxPort")
    public RobotServiceWx getDefaultRobotServiceWxPort() {
        return super.getPort(DefaultRobotServiceWxPort, RobotServiceWx.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RobotServiceWx
     */
    @WebEndpoint(name = "DefaultRobotServiceWxPort")
    public RobotServiceWx getDefaultRobotServiceWxPort(WebServiceFeature... features) {
        return super.getPort(DefaultRobotServiceWxPort, RobotServiceWx.class, features);
    }

}
