package cn.eastrobot.robotdev.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.6
 * 2015-01-27T10:10:00.689+08:00
 * Generated source version: 2.5.6
 * 
 */
@WebService(targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceWx", name = "RobotServiceWx")
@XmlSeeAlso({ObjectFactory.class})
public interface RobotServiceWx {

    @WebResult(name = "robotResponse", targetNamespace = "")
    @RequestWrapper(localName = "ask", targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceWx", className = "cn.eastrobot.robotdev.ws.client.Ask")
    @WebMethod(action = "http://www.eastrobot.cn/ws/RobotServiceWx/ask")
    @ResponseWrapper(localName = "askResponse", targetNamespace = "http://www.eastrobot.cn/ws/RobotServiceWx", className = "cn.eastrobot.robotdev.ws.client.AskResponse")
    public cn.eastrobot.robotdev.ws.client.RobotResponse ask(
        @WebParam(name = "robotRequest", targetNamespace = "")
        cn.eastrobot.robotdev.ws.client.RobotRequest robotRequest
    );
}
